## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('fake.csv',error_bad_lines = False,engine='python')

<ipython-input-12-e1ec32b21d17>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df=pd.read_csv('fake.csv',error_bad_lines = False,engine='python')
Skipping line 4433: unexpected end of data


In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
df.shape

(4431, 5)

In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
df.isnull().sum()

id          0
title     118
author    441
text       11
label       0
dtype: int64

In [ ]:
###Drop Nan Values
df=df.dropna()


In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
df.shape

(3872, 5)

In [ ]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [ ]:
## Get the Dependent features
y=df['label']

In [ ]:
X.shape

(3872, 4)

In [ ]:
y.shape

(3872,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [ ]:
messages=X.copy()

In [ ]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
messages

id                                              title  \
0        0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1        1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2        2                  Why the Truth Might Get You Fired   
3        3  15 Civilians Killed In Single US Airstrike Hav...   
4        4  Iranian woman jailed for fictional unpublished...   
...    ...                                                ...   
4424  4424  Iran’s Islamic Revolutionary Guards Corps: a d...   
4426  4426  Poll: Americans Back Donald Trump’s Immigratio...   
4427  4427  Amazon’s July 12 ‘Day of Action’ for Net Neutr...   
4429  4429  Asian-American Fighters Return to Ancestral Ho...   
4430  4430  Complete Text of President Donald Trump’s Inau...   

                  author                                               text  
0          Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...  
1        Daniel J. Flynn  Ever get the feeling your life circles the rou...  
2     Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...  
3        Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...  
4         Howard Portnoy  Print \nAn Iranian woman has been sentenced to...  
...                  ...                                                ...  
4424           The Saker  1681 Views November 15, 2016 No Comments Analy...  
4426          Neil Munro  Americans support Donald Trump’s Jan. 25 compr...  
4427    Chriss W. Street  Amazon is mobilizing a July 12 collective “Day...  
4429        Joe Cochrane  SINGAPORE  —   Brandon Vera was recently pinne...  
4430      Breitbart News  The following is the complete video and text o...  

[3872 rows x 4 columns]

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
messages

index    id                                              title  \
0         0     0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1         1     1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2         2     2                  Why the Truth Might Get You Fired   
3         3     3  15 Civilians Killed In Single US Airstrike Hav...   
4         4     4  Iranian woman jailed for fictional unpublished...   
...     ...   ...                                                ...   
3867   4424  4424  Iran’s Islamic Revolutionary Guards Corps: a d...   
3868   4426  4426  Poll: Americans Back Donald Trump’s Immigratio...   
3869   4427  4427  Amazon’s July 12 ‘Day of Action’ for Net Neutr...   
3870   4429  4429  Asian-American Fighters Return to Ancestral Ho...   
3871   4430  4430  Complete Text of President Donald Trump’s Inau...   

                  author                                               text  
0          Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...  
1        Daniel J. Flynn  Ever get the feeling your life circles the rou...  
2     Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...  
3        Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...  
4         Howard Portnoy  Print \nAn Iranian woman has been sentenced to...  
...                  ...                                                ...  
3867           The Saker  1681 Views November 15, 2016 No Comments Analy...  
3868          Neil Munro  Americans support Donald Trump’s Jan. 25 compr...  
3869    Chriss W. Street  Amazon is mobilizing a July 12 collective “Day...  
3870        Joe Cochrane  SINGAPORE  —   Brandon Vera was recently pinne...  
3871      Breitbart News  The following is the complete video and text o...  

[3872 rows x 5 columns]

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[3202, 4808, 4400, 4861, 911, 415, 4604, 137, 4357, 603],
 [2274, 4219, 1399, 4512, 660, 4833, 2319],
 [4735, 1553, 3247, 4801],
 [463, 4890, 1477, 2455, 3103, 3339],
 [1597, 660, 4231, 1959, 4779, 3455, 660, 1632, 790, 818],
 [3817,
  786,
  1509,
  2692,
  2003,
  4715,
  861,
  879,
  3207,
  3992,
  1525,
  1056,
  2992,
  1097,
  2319],
 [4662, 2297, 1000, 3733, 1902, 4041, 3218, 2565, 75, 1307, 3477],
 [2400, 175, 52, 2433, 2938, 3937, 4715, 4921, 75, 1307, 3477],
 [4854, 1607, 3995, 984, 1227, 788, 1603, 3040, 4715, 1783],
 [2045, 4522, 4710, 1540, 3427, 2836, 3683, 4857],
 [3660, 2785, 4426, 4046, 2583, 2931, 2344, 3415, 1590, 1295, 4322],
 [2455, 4630, 911, 788, 4715, 2938],
 [1101, 1204, 3887, 4723, 3042, 2976, 3722, 452, 699],
 [3851, 1564, 1304, 4163, 4768, 1738, 1497, 75, 1307, 3477],
 [3811, 3116, 2902, 2996, 1035, 75, 1307, 3477],
 [1818, 2745, 2802, 718, 390, 1106, 4858, 684, 1348, 4866],
 [2808, 3303, 4219],
 [4302, 4922, 4524, 2667, 4715, 883, 344, 2319],
 [2625, 459

In [ ]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [ ]:
onehot_repr[1]

[2274, 4219, 1399, 4512, 660, 4833, 2319]

### Embedding Representation

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[3202 4808 4400 ...    0    0    0]
 [2274 4219 1399 ...    0    0    0]
 [4735 1553 3247 ...    0    0    0]
 ...
 [3484 2482 3724 ...    0    0    0]
 [2409 1125 1397 ...    0    0    0]
 [1127  780 3970 ...    0    0    0]]


In [ ]:
embedded_docs[1]

array([2274, 4219, 1399, 4512,  660, 4833, 2319,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
embedded_docs[0]

array([3202, 4808, 4400, 4861,  911,  415, 4604,  137, 4357,  603,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(3872, (3872,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((3872, 20), (3872,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
41/41 [==============================] - 1s 21ms/step - loss: 5.0113e-05 - accuracy: 1.0000 - val_loss: 1.0884 - val_accuracy: 0.8396
Epoch 2/10
41/41 [==============================] - 1s 18ms/step - loss: 4.6282e-05 - accuracy: 1.0000 - val_loss: 1.1003 - val_accuracy: 0.8388
Epoch 3/10
41/41 [==============================] - 0s 10ms/step - loss: 4.2993e-05 - accuracy: 1.0000 - val_loss: 1.1115 - val_accuracy: 0.8388
Epoch 4/10
41/41 [==============================] - 1s 17ms/step - loss: 4.0093e-05 - accuracy: 1.0000 - val_loss: 1.1223 - val_accuracy: 0.8380
Epoch 5/10
41/41 [==============================] - 1s 20ms/step - loss: 3.7499e-05 - accuracy: 1.0000 - val_loss: 1.1330 - val_accuracy: 0.8380
Epoch 6/10
41/41 [==============================] - 0s 11ms/step - loss: 3.5179e-05 - accuracy: 1.0000 - val_loss: 1.1430 - val_accuracy: 0.8380
Epoch 7/10
41/41 [==============================] - 0s 11ms/step - loss: 3.3092e-05 - accuracy: 1.0000 - val_loss: 1.1520 - val_ac

### Adding Dropout

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
41/41 [==============================] - 6s 84ms/step - loss: 0.6362 - accuracy: 0.6099 - val_loss: 0.4014 - val_accuracy: 0.8365
Epoch 2/10
41/41 [==============================] - 2s 57ms/step - loss: 0.2736 - accuracy: 0.8863 - val_loss: 0.2840 - val_accuracy: 0.8842
Epoch 3/10
41/41 [==============================] - 2s 48ms/step - loss: 0.1228 - accuracy: 0.9607 - val_loss: 0.3882 - val_accuracy: 0.8623
Epoch 4/10
41/41 [==============================] - 1s 30ms/step - loss: 0.0749 - accuracy: 0.9749 - val_loss: 0.3150 - val_accuracy: 0.8685
Epoch 5/10
41/41 [==============================] - 1s 15ms/step - loss: 0.0483 - accuracy: 0.9880 - val_loss: 0.4009 - val_accuracy: 0.8693
Epoch 6/10
41/41 [==============================] - 1s 13ms/step - loss: 0.0274 - accuracy: 0.9923 - val_loss: 0.5039 - val_accuracy: 0.8717
Epoch 7/10
41/41 [==============================] - 1s 24ms/step - loss: 0.0199 - accuracy: 0.9961 - val_loss: 0.4693 - val_accuracy: 0.8701
Epoch 8/10
41

### Performance Metrics And Accuracy

In [ ]:
y_pred=model.predict(X_test)

40/40 [==============================] - 0s 2ms/step


In [ ]:
y_pred[1]

array([0.02069639], dtype=float32)

In [ ]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[646,  85],
       [ 83, 464]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8685446009389671

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.88      0.88       731
           1       0.85      0.85      0.85       547

    accuracy                           0.87      1278
   macro avg       0.87      0.87      0.87      1278
weighted avg       0.87      0.87      0.87      1278



In [ ]:
X_train[0]

array([1484, 4346, 1895, 3267,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
y_train[0]

1