### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [18]:
pip install --upgrade pip setuptools

In [20]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [21]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [23]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [24]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [25]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[8, 427, 491, 102], [8, 427, 491, 380], [8, 41, 491, 441], [59, 256, 76, 424, 204], [59, 256, 76, 424, 230], [302, 8, 343, 491, 461], [181, 16, 74, 424]]


### Word Embedding Represntation

In [26]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [27]:
import numpy as np

In [28]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0   8 427 491 102]
 [  0   0   0   0   8 427 491 380]
 [  0   0   0   0   8  41 491 441]
 [  0   0   0  59 256  76 424 204]
 [  0   0   0  59 256  76 424 230]
 [  0   0   0 302   8 343 491 461]
 [  0   0   0   0 181  16  74 424]]


In [29]:
## 10 feature dimesnions
dim=10


In [30]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [31]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [32]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0,   8, 427, 491, 102], dtype=int32)

In [33]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 125ms/step


array([[ 0.01126061, -0.01452177, -0.0072216 ,  0.01423246,  0.02167863,
        -0.04335613,  0.00120547, -0.02172684, -0.01988122,  0.02486568],
       [ 0.01126061, -0.01452177, -0.0072216 ,  0.01423246,  0.02167863,
        -0.04335613,  0.00120547, -0.02172684, -0.01988122,  0.02486568],
       [ 0.01126061, -0.01452177, -0.0072216 ,  0.01423246,  0.02167863,
        -0.04335613,  0.00120547, -0.02172684, -0.01988122,  0.02486568],
       [ 0.01126061, -0.01452177, -0.0072216 ,  0.01423246,  0.02167863,
        -0.04335613,  0.00120547, -0.02172684, -0.01988122,  0.02486568],
       [ 0.01419358, -0.04410331, -0.03051046,  0.03767342, -0.04282931,
         0.00997031,  0.02712512,  0.04445552,  0.01462804, -0.00251639],
       [ 0.00589002, -0.01973046,  0.00507892,  0.00811214, -0.00774512,
        -0.02935784, -0.01804046,  0.04438217, -0.04449964, -0.03997525],
       [ 0.02971429, -0.02774164, -0.01253852,  0.04296667, -0.02894956,
         0.01861875, -0.04320607, -0.0198809 

In [34]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 37ms/step
[[[ 0.01126061 -0.01452177 -0.0072216   0.01423246  0.02167863
   -0.04335613  0.00120547 -0.02172684 -0.01988122  0.02486568]
  [ 0.01126061 -0.01452177 -0.0072216   0.01423246  0.02167863
   -0.04335613  0.00120547 -0.02172684 -0.01988122  0.02486568]
  [ 0.01126061 -0.01452177 -0.0072216   0.01423246  0.02167863
   -0.04335613  0.00120547 -0.02172684 -0.01988122  0.02486568]
  [ 0.01126061 -0.01452177 -0.0072216   0.01423246  0.02167863
   -0.04335613  0.00120547 -0.02172684 -0.01988122  0.02486568]
  [ 0.01419358 -0.04410331 -0.03051046  0.03767342 -0.04282931
    0.00997031  0.02712512  0.04445552  0.01462804 -0.00251639]
  [ 0.00589002 -0.01973046  0.00507892  0.00811214 -0.00774512
   -0.02935784 -0.01804046  0.04438217 -0.04449964 -0.03997525]
  [ 0.02971429 -0.02774164 -0.01253852  0.04296667 -0.02894956
    0.01861875 -0.04320607 -0.0198809   0.04330813  0.0321796 ]
  [ 0.01664433  0.03592615  0.03095082 -0.02055854  0.03243

In [37]:
### Assignment

sente=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [36]:
voc_size = 1000

In [39]:
one_hot_rep = [one_hot(words,voc_size)for words in sente]
print(one_hot_rep)


[[238, 43, 302, 870, 503, 8], [193, 860, 302, 665, 696, 21], [630, 810, 758, 294], [238, 719, 302, 687, 238, 763], [197, 994, 351, 302, 665, 696, 21], [958, 302, 665, 696, 411, 974]]


In [43]:
sent_length=8
embedded_doc=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_doc)

[[  0   0 238  43 302 870 503   8]
 [  0   0 193 860 302 665 696  21]
 [  0   0   0   0 630 810 758 294]
 [  0   0 238 719 302 687 238 763]
 [  0 197 994 351 302 665 696  21]
 [  0   0 958 302 665 696 411 974]]


In [44]:
model.predict(embedded_doc)

1/1 [==============================] - 0s 25ms/step


array([[[ 0.01126061, -0.01452177, -0.0072216 ,  0.01423246,
          0.02167863, -0.04335613,  0.00120547, -0.02172684,
         -0.01988122,  0.02486568],
        [ 0.01126061, -0.01452177, -0.0072216 ,  0.01423246,
          0.02167863, -0.04335613,  0.00120547, -0.02172684,
         -0.01988122,  0.02486568],
        [ 0.0262705 ,  0.03033011, -0.01832972, -0.02659948,
          0.03568045,  0.01458399, -0.01190811,  0.02293407,
          0.0058458 ,  0.00895532],
        [-0.0485001 , -0.01928607, -0.0069739 ,  0.04606556,
          0.0236924 , -0.03020164, -0.00911603, -0.04842833,
          0.01279579, -0.00288894],
        [ 0.0212922 , -0.0184231 ,  0.01895389,  0.00501281,
          0.02489234,  0.00292518,  0.04993114, -0.04517186,
         -0.0161579 , -0.04417105],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0. 